import type { ContentDoc } from './content-doc.js';
import type { Section } from './sections.js';
import type { Theme, RadiusScale, ShadowScale } from './theme.js';

/**
 * Serializer — ContentDoc -> renderable build artifacts (SPEC-011).
 *
 * Produces three deterministic artifacts consumed by `landing-pages/_template`
 * at build time:
 *   - `messages/pt.json`  — i18n strings (copy per section).
 *   - `content-spec.json` — structure (enabled sections, order, field refs).
 *   - `theme.css`         — CSS custom properties derived from Theme.
 *
 * Pure: no I/O, no network. Deterministic: same ContentDoc => same artifacts
 * (supports idempotent publish). Money stays in integer cents in the spec and
 * is also exposed pre-formatted for display, derived from the same cents.
 */

export const ARTIFACT_NAMES = {
  messages: 'messages/pt.json',
  contentSpec: 'content-spec.json',
  themeCss: 'theme.css',
} as const;

export interface SerializedArtifacts {
  [ARTIFACT_NAMES.messages]: string;
  [ARTIFACT_NAMES.contentSpec]: string;
  [ARTIFACT_NAMES.themeCss]: string;
}

const RADIUS_PX: Record<RadiusScale, string> = {
  none: '0px',
  sm: '4px',
  md: '8px',
  lg: '16px',
  full: '9999px',
};

const SHADOW_CSS: Record<ShadowScale, string> = {
  none: 'none',
  sm: '0 1px 2px rgba(0,0,0,0.06)',
  md: '0 4px 12px rgba(0,0,0,0.10)',
  lg: '0 12px 32px rgba(0,0,0,0.16)',
};

/** Stable JSON stringify with sorted keys for deterministic output. */
function stableStringify(value: unknown): string {
  return JSON.stringify(sortKeys(value), null, 2);
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortKeys);
  }
  if (value !== null && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      out[key] = sortKeys((value as Record<string, unknown>)[key]);
    }
    return out;
  }
  return value;
}

/**
 * Format integer cents (BRL) for display, e.g. 19700 -> "197,00".
 * Pure and locale-stable (does not depend on the host Intl runtime).
 */
export function formatCentsBRL(cents: number): string {
  if (!Number.isInteger(cents) || cents < 0) {
    throw new Error(`formatCentsBRL expects a non-negative integer of cents, got ${cents}`);
  }
  const whole = Math.floor(cents / 100);
  const fraction = (cents % 100).toString().padStart(2, '0');
  const groupedWhole = whole.toString().replace(/\B(?=(\d{3})+(?!\d))/g, '.');
  return `${groupedWhole},${fraction}`;
}

function themeToCss(theme: Theme): string {
  const lines = [
    '/* Generated by @template/lp-render — do not edit by hand. */',
    ':root {',
    `  --color-primary: ${theme.palette.primary};`,
    `  --color-secondary: ${theme.palette.secondary};`,
    `  --color-background: ${theme.palette.background};`,
    `  --color-foreground: ${theme.palette.foreground};`,
    `  --color-accent: ${theme.palette.accent};`,
    `  --font-heading: ${theme.typography.headingFont};`,
    `  --font-body: ${theme.typography.bodyFont};`,
    `  --radius: ${RADIUS_PX[theme.radius]};`,
    `  --shadow: ${SHADOW_CSS[theme.shadow]};`,
    '}',
    '',
  ];
  return lines.join('\n');
}

/** i18n key for a section, derived from its type and position (stable). */
function sectionKey(section: Section): string {
  return `${section.type}.${section.position}`;
}

/**
 * Recursively collect display strings from a section's fields into a flat,
 * dot-namespaced message map. Numbers/booleans/urls stay in content-spec.
 */
function collectMessages(prefix: string, value: unknown, out: Record<string, string>): void {
  if (typeof value === 'string') {
    out[prefix] = value;
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((item, index) => collectMessages(`${prefix}.${index}`, item, out));
    return;
  }
  if (value !== null && typeof value === 'object') {
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      collectMessages(`${prefix}.${key}`, child, out);
    }
  }
}

/**
 * Serialize a validated ContentDoc into the three build artifacts. The input
 * MUST already be validated (parseContentDoc); serialization assumes a valid
 * closed-catalog document.
 */
export function serialize(doc: ContentDoc): SerializedArtifacts {
  const ordered = [...doc.sections].sort((a, b) => a.position - b.position);

  // messages/pt.json — copy per section, plus page title/meta.
  const messages: Record<string, string> = {};
  messages['settings.title'] = doc.settings.title;
  if (doc.settings.metaDescription !== undefined) {
    messages['settings.metaDescription'] = doc.settings.metaDescription;
  }
  for (const section of ordered) {
    collectMessages(sectionKey(section), section.fields, messages);
  }

  // content-spec.json — structure the _template reads at build time.
  const contentSpec = {
    locale: doc.settings.locale,
    noindex: doc.settings.noindex,
    title: doc.settings.title,
    ...(doc.settings.metaDescription !== undefined
      ? { metaDescription: doc.settings.metaDescription }
      : {}),
    ...(doc.settings.checkoutUrl !== undefined ? { checkoutUrl: doc.settings.checkoutUrl } : {}),
    ...(doc.settings.priceCents !== undefined
      ? {
          priceCents: doc.settings.priceCents,
          priceDisplay: formatCentsBRL(doc.settings.priceCents),
        }
      : {}),
    sections: ordered
      .filter((section) => section.enabled)
      .map((section) => ({
        type: section.type,
        position: section.position,
        version: section.version,
        key: sectionKey(section),
        fields: section.fields,
      })),
  };

  return {
    [ARTIFACT_NAMES.messages]: stableStringify(messages),
    [ARTIFACT_NAMES.contentSpec]: stableStringify(contentSpec),
    [ARTIFACT_NAMES.themeCss]: themeToCss(doc.theme),
  };
}
